export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_MORE_USERS_SUCCESS = "FETCH_MORE_USERS_SUCCESS";
export const SELECt_USER = "SELECT_USER";
export const PROFILE_STATE = "PROFILE_STATE";
